name: Build release zip

on:
    push:
        tags:
            - '*'

jobs:
    build:
        name: Build release zip
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup WP-CLI
              uses: godaddy-wordpress/setup-wp-cli@1

            - name: Run package installs and builds
              run: |
                  composer install
                  composer update

            - name: Run WordPress Coding Standard fixes
              run: vendor/bin/phpcbf --extensions=php --ignore=*/vendor/*,*/doc/*,*/svn/*,*/node_modules/*,*/gettext-helper.php,*/classes/multilingual-plugins/easy-language/pagebuilder/divi/build/,*/classes/multilingual-plugins/easy-language/blocks/*/build/,*translatepress* --standard=ruleset.xml .

            - name: Run WordPress Coding Standard checks
              run: vendor/bin/phpcs --extensions=php --ignore=*/vendor/*,*/doc/*,*/svn/*,*/node_modules/*,*/gettext-helper.php,*/classes/multilingual-plugins/easy-language/pagebuilder/divi/build/,*/classes/multilingual-plugins/easy-language/blocks/*/build/,*translatepress* --standard=ruleset.xml .

            - name: Set version number 1
              uses: richardrigutins/replace-in-files@v2
              with:
                  files: 'auto-category-for-posts.php'
                  search-text: '@@VersionNumber@@'
                  replacement-text: ${{ github.ref_name }}

            - name: Set version number 2
              uses: richardrigutins/replace-in-files@v2
              with:
                  files: 'readme.txt'
                  search-text: '@@VersionNumber@@'
                  replacement-text: ${{ github.ref_name }}

            - name: Create ZIP release
              run: |
                  rm -fr assets
                  rm -fr build
                  rm -fr releases
                  rm -fr languages
                  rm -fr changelog.md
                  rm -fr svn
                  rm readme.md
                  cd ..
                  zip -r -q ${{ github.event.repository.name }}_${{ github.ref_name }}.zip ${{ github.event.repository.name }}/* -x "*/.git/*" "*/.github/*" "*/blocks/*/src/*" "*/doc/*" "*/phpcs.xml" "*/composer.json" "*/composer.lock" "*/package.json" "*/package-lock.json" "*/.gitignore" "*/vendor/*" "*/node_modules/*" "/.editorconfig"
                  cp ${{ github.event.repository.name }}_${{ github.ref_name }}.zip ${{ github.event.repository.name }}/

            - name: Create Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  files: ${{ github.event.repository.name }}_${{ github.ref_name }}.zip
